server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: Management
          uri: http://localhost:8082
          predicates:
            - Path=/managements/** 
        - id: Driver
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/** 
        - id: orderStatus
          uri: http://localhost:8084
          predicates:
            - Path= /orderStatuses/**
        - id: HR
          uri: http://localhost:8085
          predicates:
            - Path=/hrs/**
        - id: Hrview
          uri: http://localhost:8086
          predicates:
            - Path= /hrpages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: dh-order
          uri: http://dh-order:8080
          predicates:
            - Path=/orders/** 
        - id: dh-management
          uri: http://dh-management:8080
          predicates:
            - Path=/managements/** 
        - id: dh-driver
          uri: http://dh-driver:8080
          predicates:
            - Path=/drivers/** 
        - id: dh-orderstatus
          uri: http://dh-orderstatus:8080
          predicates:
            - Path= /orderStatuses/**
        - id: dh-hr
          uri: http://dh-hr:8080
          predicates:
            - Path=/hrs/**
        - id: dh-hrview
          uri: http://dh-hrview:8080
          predicates:
            - Path= /hrpages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
